import fs from 'fs'
import {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  HeadObjectCommand,
} from '@aws-sdk/client-s3'
import { getSignedUrl } from '@aws-sdk/s3-request-presigner'

// Rendered media (video segments, thumbnails, export MP4s) lives in a
// Cloudflare R2 bucket. R2 is S3-compatible so the AWS SDK works unchanged
// against R2's endpoint. Two big reasons R2 over Supabase Storage for a
// video app:
//   1. Egress is FREE on R2 (Supabase charges $0.09/GB after free tier).
//   2. R2 storage cost is $0.015/GB vs Supabase $0.021/GB.
// For a 500-user Zieclipper deployment, R2 is ~20-30x cheaper.
//
// The bucket is private -- browsers never call R2 directly; they go through
// signed URLs generated by createSignedUrl (short-lived, per-object). That
// keeps auth in our hands via the Next.js Route Handlers, so the RLS-style
// path-prefix pattern (userId/... in mediaPath) still enforces per-user
// isolation.

const R2_ACCOUNT_ID = process.env.R2_ACCOUNT_ID
const R2_ACCESS_KEY_ID = process.env.R2_ACCESS_KEY_ID
const R2_SECRET_ACCESS_KEY = process.env.R2_SECRET_ACCESS_KEY
const R2_BUCKET = process.env.R2_BUCKET_NAME || 'zieclip'
// Prefer the jurisdiction-specific endpoint if the user copied it verbatim
// out of the R2 dashboard; otherwise assemble the generic one from the
// account id.
const R2_ENDPOINT =
  process.env.R2_ENDPOINT ||
  (R2_ACCOUNT_ID ? `https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com` : undefined)

let cachedClient: S3Client | null = null
function client(): S3Client {
  if (cachedClient) return cachedClient
  if (!R2_ENDPOINT || !R2_ACCESS_KEY_ID || !R2_SECRET_ACCESS_KEY) {
    throw new Error(
      'R2 storage not configured. Set R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, ' +
      'R2_SECRET_ACCESS_KEY (and optionally R2_BUCKET_NAME) in .env.local ' +
      'or the deployment environment.'
    )
  }
  cachedClient = new S3Client({
    region: 'auto',                 // R2 ignores region, but the SDK requires one
    endpoint: R2_ENDPOINT,
    credentials: {
      accessKeyId: R2_ACCESS_KEY_ID,
      secretAccessKey: R2_SECRET_ACCESS_KEY,
    },
    // R2 doesn't need Expect: 100-continue; disabling avoids a needless
    // handshake round-trip on every upload.
    requestChecksumCalculation: 'WHEN_REQUIRED',
    responseChecksumValidation: 'WHEN_REQUIRED',
  })
  return cachedClient
}

// Build the R2 object key. Callers still pass a Supabase user id as the
// first segment so bucket contents stay partitioned per user, matching the
// old Supabase Storage layout -- makes any future migration back or
// side-by-side coexistence a no-op.
export function mediaPath(userId: string, ...parts: string[]): string {
  return [userId, ...parts].join('/')
}

export async function uploadFile(
  storagePath: string,
  localFilePath: string,
  contentType: string,
): Promise<void> {
  const body = fs.readFileSync(localFilePath)
  await client().send(
    new PutObjectCommand({
      Bucket: R2_BUCKET,
      Key: storagePath,
      Body: body,
      ContentType: contentType,
    })
  )
}

export async function createSignedUrl(
  storagePath: string,
  ttlSeconds = 300,
): Promise<string> {
  return getSignedUrl(
    client(),
    new GetObjectCommand({ Bucket: R2_BUCKET, Key: storagePath }),
    { expiresIn: ttlSeconds }
  )
}

export async function fileExistsInStorage(storagePath: string): Promise<boolean> {
  try {
    await client().send(new HeadObjectCommand({ Bucket: R2_BUCKET, Key: storagePath }))
    return true
  } catch (err: any) {
    // HeadObject returns 404/NoSuchKey / 403/Forbidden on missing objects
    // depending on bucket policy. Both mean "not there for our purposes".
    if (err?.$metadata?.httpStatusCode === 404) return false
    if (err?.name === 'NotFound' || err?.name === 'NoSuchKey') return false
    // Any other error is an actual outage -- surface it so we don't silently
    // re-upload every time.
    if (err?.$metadata?.httpStatusCode && err.$metadata.httpStatusCode >= 500) throw err
    return false
  }
}
