import fs from 'fs'
import type { WordTiming } from '@/store/types'

function tsToSec(ts: string): number {
  const [h, m, s] = ts.split(':')
  return parseInt(h, 10) * 3600 + parseInt(m, 10) * 60 + parseFloat(s)
}

// Ported from api/services/transcript.py's parse_vtt_words. Parses
// YouTube's auto-generated VTT rolling-window format:
//
//   00:00:00.120 --> 00:00:01.870 align:start position:0%
//   learning<00:00:00.480><c> how</c><00:00:00.599><c> to</c>...
//
// - First text line is previous/empty accumulated text (skipped)
// - Second text line: first word starts at cue_start, then <ts><c> word</c>
//   for each subsequent word
// - Cues without <c> tags are rolling-window duplicates (already-seen text
//   repeated) and must be skipped, or every phrase appears twice.
export function parseVttWords(vttPath: string): WordTiming[] {
  const content = fs.readFileSync(vttPath, 'utf-8')
  const rawEntries: Array<[number, string]> = []

  const isAutoGenerated = content.includes('<c>')
  const cueBlocks = content.trim().split(/\n\n+/)

  for (const block of cueBlocks) {
    const lines = block.trim().split(/\r?\n/)
    const arrowIdx = lines.findIndex((l) => l.includes('-->'))
    if (arrowIdx === -1) continue

    const arrowLine = lines[arrowIdx]
    const cueStartMatch = arrowLine.match(/(\d{2}:\d{2}:\d{2}\.\d{3})/)
    if (!cueStartMatch) continue
    const cueStart = tsToSec(cueStartMatch[1])

    const textLines = lines.slice(arrowIdx + 1)
    const activeLine = textLines.find((l) => l.includes('<c>'))

    if (!activeLine) {
      if (isAutoGenerated) continue // rolling-window duplicate, skip

      // Plain VTT (manual subs): no per-word timing, distribute proportionally
      const cueEndMatch = arrowLine.match(/-->\s*(\d{2}:\d{2}:\d{2}\.\d{3})/)
      const cueEnd = cueEndMatch ? tsToSec(cueEndMatch[1]) : cueStart + 2.0
      const plainText = textLines
        .filter((l) => l.trim() && !l.startsWith('NOTE') && !l.includes('-->'))
        .map((l) => l.replace(/<[^>]+>/g, '').trim())
        .join(' ')
        .trim()
      const plainWords = plainText.split(/\s+/).filter(Boolean)
      if (plainWords.length) {
        const dur = (cueEnd - cueStart) / plainWords.length
        plainWords.forEach((w, i) => {
          rawEntries.push([Math.round((cueStart + i * dur) * 1000) / 1000, w])
        })
      }
      continue
    }

    const firstWordMatch = activeLine.match(/^([^<\n]+)/)
    if (firstWordMatch) {
      const word = firstWordMatch[1].trim()
      if (word) rawEntries.push([cueStart, word])
    }

    const wordTagRe = /<(\d{2}:\d{2}:\d{2}\.\d{3})><c>(.*?)<\/c>/g
    let m: RegExpExecArray | null
    while ((m = wordTagRe.exec(activeLine))) {
      const ts = tsToSec(m[1])
      const word = m[2].trim()
      if (word) rawEntries.push([ts, word])
    }
  }

  if (!rawEntries.length) return []

  rawEntries.sort((a, b) => a[0] - b[0])

  const result: WordTiming[] = []
  for (let i = 0; i < rawEntries.length; i++) {
    const [start, word] = rawEntries[i]
    let end = i + 1 < rawEntries.length ? rawEntries[i + 1][0] : start + 0.5
    if (end <= start) end = start + 0.3
    result.push({ word, start: Math.round(start * 1000) / 1000, end: Math.round(end * 1000) / 1000 })
  }

  return deduplicate(result)
}

// Removes duplicate words left over from overlapping VTT rolling-window cues.
function deduplicate(words: WordTiming[]): WordTiming[] {
  if (!words.length) return words
  const result: WordTiming[] = [words[0]]
  for (let i = 1; i < words.length; i++) {
    const w = words[i]
    const prev = result[result.length - 1]
    if (w.word.toLowerCase() === prev.word.toLowerCase() && Math.abs(w.start - prev.start) < 0.15) continue
    result.push(w)
  }
  return result
}
