import type { EditorSettings } from '@/store/types'

type PresetSettings = Omit<EditorSettings, 'crop' | 'trim' | 'subtitleOffsetMs'>

export const SUBTITLE_PRESETS: Record<string, PresetSettings> = {
  MrBeast: {
    subtitleStyle: {
      preset: 'MrBeast',
      transition: 'pop',
      splitMode: 'byWordCount',
      splitValue: 3,
      position: 'bottom',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Impact',
      size: 80,
      weight: '900',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 8,
      highlightColor: '#FFD700',
      highlightEffect: 'both',
      uppercase: true,
      italic: false,
    },
    emoji: { enabled: false, position: 'above', size: 60, animation: 'bounce', autoGenerate: false, overrides: {} },
  },
  'TikTok Bold': {
    subtitleStyle: {
      preset: 'TikTok Bold',
      transition: 'word-by-word',
      splitMode: 'byWordCount',
      splitValue: 4,
      position: 'center',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Montserrat',
      size: 72,
      weight: '800',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 5,
      highlightColor: '#FF0050',
      highlightEffect: 'color',
      uppercase: true,
      italic: false,
    },
    emoji: { enabled: true, position: 'above', size: 64, animation: 'pop', autoGenerate: true, overrides: {} },
  },
  Karaoke: {
    subtitleStyle: {
      preset: 'Karaoke',
      transition: 'karaoke',
      splitMode: 'byWordCount',
      splitValue: 6,
      position: 'bottom',
      positionOffsetY: 0,
      background: { enabled: true, color: '#000000B3', padding: 12, borderRadius: 8 },
    },
    font: {
      family: 'Montserrat',
      size: 60,
      weight: '700',
      color: '#AAAAAA',
      strokeColor: '#000000',
      strokeWidth: 2,
      highlightColor: '#00FF88',
      highlightEffect: 'color',
      uppercase: false,
      italic: false,
    },
    emoji: { enabled: false, position: 'above', size: 48, animation: 'none', autoGenerate: false, overrides: {} },
  },
  Subtitles: {
    subtitleStyle: {
      preset: 'Subtitles',
      transition: 'fade',
      splitMode: 'byWordCount',
      splitValue: 7,
      position: 'bottom',
      positionOffsetY: 0,
      background: { enabled: true, color: '#000000BF', padding: 10, borderRadius: 4 },
    },
    font: {
      family: 'Arial',
      size: 52,
      weight: '400',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 0,
      highlightColor: '#FFFF00',
      highlightEffect: 'color',
      uppercase: false,
      italic: false,
    },
    emoji: { enabled: false, position: 'above', size: 48, animation: 'none', autoGenerate: false, overrides: {} },
  },
  'Clean White': {
    subtitleStyle: {
      preset: 'Clean White',
      transition: 'slide',
      splitMode: 'byWordCount',
      splitValue: 5,
      position: 'bottom',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Helvetica Neue',
      size: 64,
      weight: '700',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 4,
      highlightColor: '#FFFFFF',
      highlightEffect: 'scale',
      uppercase: false,
      italic: false,
    },
    emoji: { enabled: false, position: 'above', size: 48, animation: 'none', autoGenerate: false, overrides: {} },
  },
  Neon: {
    subtitleStyle: {
      preset: 'Neon',
      transition: 'pop',
      splitMode: 'byWordCount',
      splitValue: 4,
      position: 'center',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Impact',
      size: 76,
      weight: '900',
      color: '#00FFFF',
      strokeColor: '#0000FF',
      strokeWidth: 6,
      highlightColor: '#FF00FF',
      highlightEffect: 'both',
      uppercase: true,
      italic: false,
    },
    emoji: { enabled: true, position: 'above', size: 56, animation: 'spin', autoGenerate: true, overrides: {} },
  },
}

export const DEFAULT_SETTINGS: EditorSettings = {
  subtitleStyle: SUBTITLE_PRESETS.MrBeast.subtitleStyle,
  font: SUBTITLE_PRESETS.MrBeast.font,
  emoji: SUBTITLE_PRESETS.MrBeast.emoji,
  crop: {
    x: (1 - (9 * 9) / (16 * 16)) / 2,
    width: (9 * 9) / (16 * 16),
    background: 'blur',
    backgroundColor: '#000000',
    style: 'fill',
    startOffset: 0,
    endOffset: 0
  },
  trim: { start: 0, end: 0 },
  subtitleOffsetMs: 0,
}
