import type { EditorSettings } from '@/store/types'

// videoFormat is intentionally excluded: a caption preset shouldn't force an
// aspect ratio (the user picks 9:16 / 1:1 / 16:9 separately in CropPanel).
type PresetSettings = Omit<EditorSettings, 'crop' | 'trim' | 'subtitleOffsetMs' | 'videoFormat'>

// Caption presets inspired by the popular short-form styles (openclip-style
// lineup). Each is a full subtitleStyle + font + emoji bundle applied by
// editorStore.applyPreset. Names are descriptive of the look, not brands.
export const SUBTITLE_PRESETS: Record<string, PresetSettings> = {
  Beast: {
    subtitleStyle: {
      preset: 'Beast',
      transition: 'pop',
      splitMode: 'byWordCount',
      splitValue: 3,
      position: 'center',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Impact',
      size: 84,
      weight: '900',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 8,
      highlightColor: '#FFD400',
      highlightEffect: 'both',
      uppercase: true,
      italic: false,
    },
    emoji: { enabled: true, position: 'above', size: 64, animation: 'bounce', autoGenerate: true, overrides: {} },
  },
  Hormozi: {
    subtitleStyle: {
      preset: 'Hormozi',
      transition: 'word-by-word',
      splitMode: 'byWordCount',
      splitValue: 3,
      position: 'center',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Montserrat',
      size: 80,
      weight: '900',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 7,
      highlightColor: '#22FF66',
      highlightEffect: 'both',
      uppercase: true,
      italic: false,
    },
    emoji: { enabled: true, position: 'above', size: 60, animation: 'pop', autoGenerate: true, overrides: {} },
  },
  Pop: {
    subtitleStyle: {
      preset: 'Pop',
      transition: 'pop',
      splitMode: 'byWordCount',
      splitValue: 4,
      position: 'center',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Montserrat',
      size: 74,
      weight: '800',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 5,
      highlightColor: '#FF2D75',
      highlightEffect: 'color',
      uppercase: true,
      italic: false,
    },
    emoji: { enabled: true, position: 'above', size: 60, animation: 'pop', autoGenerate: true, overrides: {} },
  },
  'TikTok Bold': {
    subtitleStyle: {
      preset: 'TikTok Bold',
      transition: 'word-by-word',
      splitMode: 'byWordCount',
      splitValue: 4,
      position: 'center',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Montserrat',
      size: 72,
      weight: '800',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 5,
      highlightColor: '#FF0050',
      highlightEffect: 'color',
      uppercase: true,
      italic: false,
    },
    emoji: { enabled: true, position: 'above', size: 64, animation: 'pop', autoGenerate: true, overrides: {} },
  },
  Karaoke: {
    subtitleStyle: {
      preset: 'Karaoke',
      transition: 'karaoke',
      splitMode: 'byWordCount',
      splitValue: 6,
      position: 'bottom',
      positionOffsetY: 0,
      background: { enabled: true, color: '#000000B3', padding: 12, borderRadius: 8 },
    },
    font: {
      family: 'Montserrat',
      size: 60,
      weight: '700',
      color: '#AAAAAA',
      strokeColor: '#000000',
      strokeWidth: 2,
      highlightColor: '#00FF88',
      highlightEffect: 'color',
      uppercase: false,
      italic: false,
    },
    emoji: { enabled: false, position: 'above', size: 48, animation: 'none', autoGenerate: false, overrides: {} },
  },
  Highlight: {
    subtitleStyle: {
      preset: 'Highlight',
      transition: 'none',
      splitMode: 'byWordCount',
      splitValue: 5,
      position: 'center',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Montserrat',
      size: 70,
      weight: '800',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 5,
      highlightColor: '#FFD400',
      highlightEffect: 'color',
      uppercase: false,
      italic: false,
    },
    emoji: { enabled: false, position: 'above', size: 52, animation: 'none', autoGenerate: false, overrides: {} },
  },
  Subtitles: {
    subtitleStyle: {
      preset: 'Subtitles',
      transition: 'fade',
      splitMode: 'byWordCount',
      splitValue: 7,
      position: 'bottom',
      positionOffsetY: 0,
      background: { enabled: true, color: '#000000BF', padding: 10, borderRadius: 4 },
    },
    font: {
      family: 'Arial',
      size: 52,
      weight: '400',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 0,
      highlightColor: '#FFFF00',
      highlightEffect: 'color',
      uppercase: false,
      italic: false,
    },
    emoji: { enabled: false, position: 'above', size: 48, animation: 'none', autoGenerate: false, overrides: {} },
  },
  'Clean White': {
    subtitleStyle: {
      preset: 'Clean White',
      transition: 'slide',
      splitMode: 'byWordCount',
      splitValue: 5,
      position: 'bottom',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Helvetica Neue',
      size: 64,
      weight: '700',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 4,
      highlightColor: '#FFFFFF',
      highlightEffect: 'scale',
      uppercase: false,
      italic: false,
    },
    emoji: { enabled: false, position: 'above', size: 48, animation: 'none', autoGenerate: false, overrides: {} },
  },
  Minimal: {
    subtitleStyle: {
      preset: 'Minimal',
      transition: 'fade',
      splitMode: 'byWordCount',
      splitValue: 4,
      position: 'bottom',
      positionOffsetY: 40,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Arial',
      size: 56,
      weight: '700',
      color: '#FFFFFF',
      strokeColor: '#000000',
      strokeWidth: 3,
      highlightColor: '#FFFFFF',
      highlightEffect: 'color',
      uppercase: false,
      italic: false,
    },
    emoji: { enabled: false, position: 'above', size: 44, animation: 'none', autoGenerate: false, overrides: {} },
  },
  Neon: {
    subtitleStyle: {
      preset: 'Neon',
      transition: 'pop',
      splitMode: 'byWordCount',
      splitValue: 4,
      position: 'center',
      positionOffsetY: 0,
      background: { enabled: false, color: '#00000000', padding: 0, borderRadius: 0 },
    },
    font: {
      family: 'Impact',
      size: 76,
      weight: '900',
      color: '#00FFFF',
      strokeColor: '#0000FF',
      strokeWidth: 6,
      highlightColor: '#FF00FF',
      highlightEffect: 'both',
      uppercase: true,
      italic: false,
    },
    emoji: { enabled: true, position: 'above', size: 56, animation: 'spin', autoGenerate: true, overrides: {} },
  },
  Cinematic: {
    subtitleStyle: {
      preset: 'Cinematic',
      transition: 'fade',
      splitMode: 'bySentence',
      splitValue: 8,
      position: 'bottom',
      positionOffsetY: 0,
      background: { enabled: true, color: '#00000099', padding: 8, borderRadius: 2 },
    },
    font: {
      family: 'Georgia',
      size: 54,
      weight: '400',
      color: '#F5F5F5',
      strokeColor: '#000000',
      strokeWidth: 1,
      highlightColor: '#F5D06A',
      highlightEffect: 'color',
      uppercase: false,
      italic: true,
    },
    emoji: { enabled: false, position: 'above', size: 44, animation: 'none', autoGenerate: false, overrides: {} },
  },
}

export const DEFAULT_SETTINGS: EditorSettings = {
  subtitleStyle: SUBTITLE_PRESETS.Beast.subtitleStyle,
  font: SUBTITLE_PRESETS.Beast.font,
  emoji: SUBTITLE_PRESETS.Beast.emoji,
  crop: {
    x: (1 - (9 * 9) / (16 * 16)) / 2,
    width: (9 * 9) / (16 * 16),
    background: 'blur',
    backgroundColor: '#000000',
    style: 'fill',
    startOffset: 0,
    endOffset: 0
  },
  trim: { start: 0, end: 0 },
  subtitleOffsetMs: 0,
  videoFormat: '9:16',
}
